---
apiVersion: v2
name: gitlab-ci-pipelines-exporter
version: 0.3.6-bb.7
appVersion: v0.5.10
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
dependencies:
  - name: gluon
    version: 0.8.0
    repository: oci://registry1.dso.mil/bigbang
  - name: redis
    version: 22.0.3-bb.0
    repository: oci://registry1.dso.mil/bigbang
    condition: redis-bb.enabled
    alias: redis-bb
annotations:
  bigbang.dev/maintenanceTrack: bb_maintained
  bigbang.dev/applicationVersions: |
    - gitlab-ci-pipelines-exporter: v0.5.10
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    The [upstream chart's release notes](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/CHANGELOG.md) may help when reviewing this package.
  helm.sh/images: |
    - name: gitlab-ci-pipelines-exporter
      image: registry1.dso.mil/ironbank/opensource/gitlab-ci-pipelines-exporter:v0.5.10
    - name: redis
      image: registry1.dso.mil/ironbank/bitnami/redis:8.2.0
      condition: redis-bb.enabled
    - name: redis-exporter
      image: registry1.dso.mil/ironbank/bitnami/analytics/redis-exporter:v1.75.0
      condition: redis-bb.enabled
    - name: kubectl
      condition: gcpeJob.enabled
      image: registry1.dso.mil/ironbank/gitlab/gitlab/kubectl:18.2.2