---
apiVersion: v2
name: gitlab-ci-pipelines-exporter
version: 0.3.5-bb.0
appVersion: v0.5.10
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
dependencies:
  - name: gluon
    version: 0.5.14
    repository: oci://registry1.dso.mil/bigbang
  - name: redis
    version: 20.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis-bb.enabled
    alias: redis-bb
annotations:
  bigbang.dev/maintenanceTrack: bb_maintained
  bigbang.dev/applicationVersions: |
    - gitlab-ci-pipelines-exporter: v0.5.10
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    The [upstream chart's release notes](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/CHANGELOG.md) may help when reviewing this package.
helm.sh/images: |
    - name: redis
      image: registry1.dso.mil/ironbank/bitnami/redis:7.4.2
      condition: redis-bb.enabled
