{{- if .Values.networkPolicies.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:  
  name: prometheus-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: prometheus
  portLevelMtls:
    "8080":
      mode: PERMISSIVE
{{- end }}
