apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-gitlab-internal
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  egress:
    - ports:
        - protocol: TCP
          port: 8181
  policyTypes:
    - Egress
