{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  annotations:
    {{- with .Values.serviceMonitor.annotations }}
      {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port }}
      interval: {{ .interval }}
      {{- if .scheme }}
      scheme: {{ .scheme }}
      {{- end }}
      {{- if .tlsConfig }}
      tlsConfig:
        {{- if .tlsConfig.caFile }}
        caFile: {{ .tlsConfig.caFile }}
        {{- end }}
        {{- if .tlsConfig.certFile }}
        certFile: {{ .tlsConfig.certFile }}
        {{- end }}
        {{- if .tlsConfig.keyFile }}
        keyFile: {{ .tlsConfig.keyFile }}
        {{- end }}
        {{- if .tlsConfig.insecureSkipVerify }}
        insecureSkipVerify: {{ .tlsConfig.insecureSkipVerify }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}