{{- if .Values.gcpeJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: exporter-token-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
{{- end }}
