{{- if .Values.networkPolicies.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-within-namespace
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["gitlab-ci-pipelines-exporter"]
{{- end }}